### ISSUE TITLE
nice stuff

### ISSUE THREAD

**Issue by ArjixWasTaken** [voidfill/multistickers#1]
Vencord has a nice replacement shortcut named `$self` iirc, it expands to  `Vencord.Plugins.plugins["multistickers"]`

https://github.com/voidfill/multistickers/blob/main/index.tsx#L80

https://github.com/Vendicated/Vencord/blob/main/src/utils/patches.ts#L28-L35

**Comment by voidfill** [comment]
idk why this is an issue but 3a5fbe0

**Comment by ArjixWasTaken** [comment]
It was a tip
